## Day 3 assignment

#### Installing pandas and numpy

In [1]:
! pip install pandas

In [2]:
! pip install numpy

#### Creating a 2D 3x3 array

In [4]:
import numpy as np
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Multiplying each element in array by 2

In [5]:
#multiplying 2 to each element of array and store in new array
arr2d_mult=arr2d*2
print(arr2d_mult)


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


#### Creating a dataframe of products using dictionary

In [7]:
import pandas as pd
data={'product_name':['Soap','Brush','Powder'],
      'product_price':[100,200,300],
      'product_quantity':[40,60,100]}
df=pd.DataFrame(data)
print(df)


  product_name  product_price  product_quantity
0         Soap            100                40
1        Brush            200                60
2       Powder            300               100


#### Filtering products whose quantity is greater than 50

In [8]:
#printing the products with quantity more than 50
print(df[df['product_quantity']>50])

  product_name  product_price  product_quantity
1        Brush            200                60
2       Powder            300               100
